### ISSUE TITLE
JSON schema support

### ISSUE THREAD

**Issue by bas-velthuizen** [secretfader/distill#3]
Hi Nicolas, great library.
Any chance of JSON schema support being added?
(http://json-schema.org/)
Kind regards,
Bas

**Comment by secretfader** [comment]
Hey Bas,

What exactly are you looking for? I'm not 100% sure what JSON Schema is, and I'd love to hear more about it before I give an answer. 

Nicholas

**Comment by secretfader** [comment]
Never mind my previous comment. You included a link with more information, but Github didn't include it in the notification email (and as I'm mobile at this time, email is the best way to comment).

That's exactly where I hope to go.... be it with Distill, or another library that works in tandem with it.

Some of the concepts of JSON schema may not fit the basic idea of Distill very well, but the sort of APIs described in the JSON schema docs, are the ones I find myself building over and over again. It's a huge pain to rebuild serialization from scratch - and that is - in part, why this library exists. 

I'll keep you in the loop as I push the library forward. I have a major rewrite planned, which should make tweaking the serializers - and how they behave - rather trivial.

**Comment by secretfader** [comment]
This will happen as a part of #1 .
