### ISSUE TITLE
Add support for renaming fields

### ISSUE THREAD

**Issue by scottksmith95** [secretfader/distill#4]
A function that allows renaming fields would be very useful with this library.

Something like:

``` JavaScript
var output =
  distill(data)
    .rename('_id', 'id')
    .field('id')
    .field('title')
    .embed('authors', 'id')
    .bottle();
```

**Comment by secretfader** [comment]
This is already possible. Take a look at the tests, and see where I use aliases for details, but essentially, it works like this:

``` javascript
var output = distill(data)
  .field('id', '_id')
  .bottle();
```

The outputted object will have an `id` field instead of `_id`.

**Comment by scottksmith95** [comment]
Awesome! I didn't realize that was supported. The only thing I would suggest is updating the Usage documentation to show this.

Great work on this btw. I am already using it in a project.

**Comment by secretfader** [comment]
Awesome! I didn't know it was being used by anyone but me. ;)

I'll tweak the Readme now.
