### ISSUE TITLE
Add support for excluding fields

### ISSUE THREAD

**Issue by scottksmith95** [secretfader/distill#5]
You can include fields using the .fields function. It would very useful to have an .excludes function.

Something like

``` JavaScript
var output =
  distill(data)
    .exclude('__v')
    .bottle();
```

**Comment by secretfader** [comment]
By default, Distill doesn't output any fields that you don't include. The whole idea (for me) was to only include fields I cared about.

That said, I might build in something like this in the next version. But for now, I'll put it on hold. I'm planning v2, but it won't happen until I've decided how to resolve #1 .

That said, if you want to pitch in a pull request, go for it. My hands are kinda full at the moment.

**Comment by scottksmith95** [comment]
No problem. I can see cases where inclusion makes the most sense and others where exclusion would be better. I had a case where I wanted to exclude one field but ended up included 10 fields.

If I find some free time I will tinker around with implementing exclusions. The challenge I see is how best to build an API that works well to support inclusion or exclusion. It doesn't make sense to have both used at the same time.

**Comment by secretfader** [comment]
My initial idea is to extend Object and Array, the two main objects that Distill deals with, and add the appropriate filtering logic to those new objects. That should make everything _a lot_ cleaner. If both `DistillObject` and `DistillArray` have filtering methods, I think that would make this sort of thing a lot simpler.
